🫐 Use cc crate for compilation
Vurich/astcenc-sys pull request #3
Opened 2024-12-09 17:02 UTC by rosaliedewinther

This PR does a few separate things:
 - Bump bindgen
 - Use cc instead of cmake for building. This simplifies both the build.rs and linking to this crate. 
 - Output the bindgen.rs file to the src directory. This allows us to track api changes as well as making things like jump to definition not open a file very deep in your target folder (or even non existent before building).
 - Remove now unneeded `wrapper.h`

2024-12-19 15:21 UTC, eira-fransham requested changes
Love this change, as it makes compilation a lot more seamless. I have some issues, however:

- The build script now dumps the bindings file into the source directory. This is incorrect - build scripts should never edit the source directory.
- This removes the `wrapper.h` file - this is not necessarily incorrect, but it does mean that our top-level header is now in external code. I think this should be reverted, as it is generally considered to be better form to have a top-level header which just does `#include <some-library.h>` and then use the C compiler's header search mechanisms to find the relevant headers.
- This makes it impossible to use a version of astenc supplied by e.g. the distribution. I think it would be better to use feature flags.

For an example of what I mean by using feature flags, you could have this in the `Cargo.toml`

```toml
[build-dependencies]
bindgen = "0.70"
pkg-config = { version = "0.3", optional = true }
cc = "1.2"

[features]
default = ["vendored"]
vendored = ["pkg-config"]
```

(Note that we're still getting rid of cmake and using cc for compilation of the vendored astenc)

Then in the build script, instead of trying to probe and falling back to the vendored library if it is not found, we probe if `vendored` is not set and fail if it is not found, and if `vendored` _is_ set we don't even try to probe and just use `cc` to compile.

Sorry for the relatively harsh review, I am really happy with the concept behind this change and I have no issues with the way that `cc` was used for compilation. I just think that there should be an option to use the distro version of astenc - plus I think that the changes to how bindgen is used should be reverted.

2024-12-19 15:21 UTC, eira-fransham commented on build.rs
> +        .write_to_file("src/bindings.rs")
This should use `bindings_path`, the bindings should be generated at compile-time not be committed to the repository.

2024-12-19 15:21 UTC, eira-fransham commented on src/lib.rs
> +include!("bindings.rs");
This should be reverted - the bindings should not be committed to the repository they should be generated at compile-time.

2025-01-09 15:53 UTC, eira-fransham requested changes
Looks good for now, I know I said before that I wanted it to be possible to use the OS's astcenc but I've actually changed my mind and I'm happy for this to only allow the vendored version of the C++ lib. I may want to change it in the future to allow choosing vendored vs OS astc releases but for now this is fine and it reduces the amount that needs to be tested. The only issue is that the build script still compiles the `astcenc.h` file instead of using the `wrapper.h` file - `main_header` should be changed and `astc-encoder/Source` should be added to the header search paths using `.clang_arg("-Iastc-encoder/Source")` (might need to do string interpolation if `clang_arg` requires an absolute path rather than a relative one).

Also, this should be rebased on master.

2025-01-09 15:53 UTC, eira-fransham commented on build.rs
> +        .write_to_file(bindings_path)
Perfect, thank you!

2025-01-09 15:53 UTC, eira-fransham commented on wrapper.h
> +#include <astcenc.h>
This file was added but the build script still uses the full path to `astcenc.h`

2025-01-09 16:23 UTC, rosaliedewinther commented
I think this now covers most your requests

2025-01-09 16:43 UTC, eira-fransham commented
Fantastic, thank you!

2025-01-09 16:43 UTC, merged

2025-01-24 13:32 UTC, tomaka commented
The C++ compilation fails on my MacOS machine due to missing compiler flags.
These flags probably should have been replicated: https://github.com/ARM-software/astc-encoder/blob/3efe1501219432a5ed07c4cea8c2ea6f90e3abb0/CMakeLists.txt#L30-L34

In general, I'm really not sure that it's a good idea to just completely ignore their CMakeLists.txt without any CI in place. Their source code seems to be heavily dependent on the content of their CMakeLists.txt, and the fact that it "just works" on Linux might be a coincidence.

2025-01-24 13:37 UTC, eira-fransham commented
> The C++ compilation fails on my MacOS machine due to missing compiler flags. These flags probably should have been replicated: https://github.com/ARM-software/astc-encoder/blob/3efe1501219432a5ed07c4cea8c2ea6f90e3abb0/CMakeLists.txt#L30-L34
> 
> In general, I'm really not sure that it's a good idea to just completely ignore their CMakeLists.txt without any CI in place. Their source code seems to be heavily dependent on the content of their CMakeLists.txt, and the fact that it "just works" on Linux might be a coincidence.

Thanks @tomaka, it's a bit difficult to find a good middle-ground because on the one hand using their cmake means that the default flags "just work", which is why I used it in the first place, but using `cc` means that compilation follows cargo's build config automatically.

2025-01-24 14:22 UTC, tomaka commented
> using cc means that compilation follows cargo's build config automatically.

The `cmake` crate is designed to do that as well.
I don't know which issue this PR is meant to fix, so I don't really know why you're thinking that this is not the case.

2025-01-27 10:44 UTC, eira-fransham commented
> > using cc means that compilation follows cargo's build config automatically.
> 
> The `cmake` crate is designed to do that as well. I don't know which issue this PR is meant to fix, so I don't really know why you're thinking that this is not the case.

I don't know about how it is now, but I do remember having issues with the `cmake` crate not taking into account certain flags automatically - possibly this is because `astcenc`'s makefile requires certain bespoke flags to be set. Either way, it's been a while since I've actually used this library in anger so it's possible that I've misjudged including this change.